Repository checkdigit/github-actions, pull requests merged in 2022-09, with the labels that each got.

#2 Initial version
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/publish.yml
  .gitignore
  README.md
  bin/action
  package-lock.json
  package.json
  src/command.ts
  src/github-context.spec.ts
  src/github-publish-comment.spec.ts
  src/github.spec.ts
  src/github.ts
  src/index.ts
  src/nocks/github.test.ts
  src/package.spec.ts
  src/package.ts
  src/short-id.spec.ts
  src/short-id.ts
  tsconfig.json
Labels: MAJOR

#5 Publish needs write access - repository public npm publish should be to
  .github/workflows/publish.yml
  package.json
Labels: PATCH

#6 Added lcov reporter implementation
  .github/workflows/codeql-analysis.yml
  SECURITY.md
  coverage-reporter/action.yml
  package-lock.json
  package.json
  setup.mjs
  src/coverage-reporter/LICENSE.lcov-parse.txt
  src/coverage-reporter/LICENSE.lcov-reporter-action.txt
  src/coverage-reporter/cli.ts
  src/coverage-reporter/comment.ts
  src/coverage-reporter/delete-old-comments.ts
  src/coverage-reporter/get-changes.ts
  src/coverage-reporter/html.spec.ts
  src/coverage-reporter/html.ts
  src/coverage-reporter/index.ts
  src/coverage-reporter/lcov.spec.ts
  src/coverage-reporter/lcov.ts
  src/coverage-reporter/options.ts
  src/coverage-reporter/tabulate.spec.ts
  src/coverage-reporter/tabulate.ts
  src/coverage-reporter/util.spec.ts
  src/coverage-reporter/util.ts
Labels: MINOR

#7 Fix setup path
  coverage-reporter/action.yml
  setup.mjs
  src/coverage-reporter/delete-old-comments.ts
  src/coverage-reporter/get-changes.ts
  src/coverage-reporter/index.ts
  src/coverage-reporter/util.ts
Labels: PATCH

#10 Convert publish beta command to action
  .github/workflows/publish.yml
  publish-beta/action.yml
  src/publish-beta/command.ts
  src/publish-beta/github-context.spec.ts
  src/publish-beta/github-publish-comment.spec.ts
  src/publish-beta/github.spec.ts
  src/publish-beta/github.ts
  src/publish-beta/index.ts
  src/publish-beta/package.spec.ts
  src/publish-beta/package.ts
  src/publish-beta/short-id.spec.ts
  src/publish-beta/short-id.ts
Labels: MINOR
